# Generated by Django 3.0.8 on 2020-08-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='desc',
            field=models.TextField(default='default desc', max_length=255),
            preserve_default=False,
        ),
    ]
